### ISSUE TITLE
NullPointerException at com.exacttarget.etpushsdk.ETSendDataIntentService.onHandleIntent

### ISSUE THREAD

**Issue by debaj** [ExactTarget/JB4A-SDK-Android#5]
Dear ExactTarget devs,

We have these bug reports pop up occasionally in our app:

java.lang.NullPointerException at com.exacttarget.etpushsdk.ETSendDataIntentService.onHandleIntent(SourceFile:82)" at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)" at android.os.Handler.dispatchMessage(Handler.java:102)" at android.os.Looper.loop(Looper.java:136)"

Currently we are using the ET Push SDK v3.4.1.

Other info: these bug reports come from the live app on various devices and locale settings in a relatively low number, we can not reproduce the issue. This bug resurfaces after every library update since we started using Exact Target, with SDK version 3.0.

**Comment by androidfu** [comment]
The only time this error presents itself is if you are overriding ETSendDataIntentService and failing to include Extras.  We have never seen this crash in-the-wild from the provided class.

If you would like to further the discussion please open a question on StackExchange http://salesforce.stackexchange.com/tags/exacttarget
