### ISSUE TITLE
Almost a ANR when Google Play Services is not enabled

### ISSUE THREAD

**Issue by fcduarte** [ExactTarget/JB4A-SDK-Android#6]
Hi all,

when Google Play Services is not enabled, the SDK Explorer app takes almost 30 seconds to start. Please take a look on this video to see the problem in action:

https://s3.amazonaws.com/uploads.hipchat.com/190289/1638059/ofdGOsp1lteFYkb/device-2015-05-14-133223.mp4

Steps to reproduce:

1. Go to Settings -> Apps -> All
2. Find Google Play Services, disable and stop it
3. Open SDK Explorer

What worries me most is not even this problem but all the code that might have been executed on `onCreate()` of `Application` class .. I'm in the middle of an integration and this could be a deal breaker, could you guys take a look on it?

Let me know if more input is needed.

Thanks,

**Comment by androidfu** [comment]
We are aware of the issue and it has been resolved in our next release.  Thank you!
