### ISSUE TITLE
Don't warn about Google Play Services on Android Emulator/Genymotion

### ISSUE THREAD

**Issue by fcduarte** [ExactTarget/JB4A-SDK-Android#7]
Despite the issue #6 even if it's fixed it'll be strange to be warned about Google Play Services on a emulator every time that you run the app.

Even better, as a feature request, the SDK could provide a method to opt-out being notified when GPS is not installed. For me it's weird that a third-party library create notifications on the behalf of my app without asking for it.

**Comment by androidfu** [comment]
@fcduarte The problem is Google Play Services are a mandatory requirement.  If you do not have Google Play Services installed then you cannot use our SDK.  Warning on application startup is considered a best practice by Google themselves.
